### ISSUE TITLE
Improve debugability of `NetworkInterface`s

### ISSUE THREAD

**Issue by lukasfrank** [ironcore-dev/metalnet#247]
# Summary

Currently, it's difficult to find out the reason if a `NetworkInterface` is in `Error` state. 

## Basic example

Creating two `NetworkInterface`s using the same IP obviously result in an `Error` state for the second NIC. It would helpful to have the reason attached to the object. 

## Possible approaches 

1. Extending the state using `status.conditions`
other kubernetes objects follow the same pattern. e.g. pods: 
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T13:20:16Z"
    status: "True"
    type: PodScheduled
```

2. Fire an `Event` 
Using `Event`s and referencing the involved object can help to understand the state of an object by running `k describe <obj>`

e.g. pod events
```
Name:             dp-service-bf-tcrns
Namespace:        dp-service-bf-system
....
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Normal   Created           20m                 kubelet            Created container init-dp-service
  Normal   Started           20m                 kubelet            Started container init-dp-service
```
