### ISSUE TITLE
`LoadBalancer` for non-public networks - Internal Load Balancer

### ISSUE THREAD

**Issue by adracus** [ironcore-dev/metalnet#35]
# Summary

The current `LoadBalancer` implementation always announces routes to the `metalbond` 'public' VNI:
https://github.com/onmetal/metalnet/blob/eb0848dd1e6a749dd8119bb65328d2b0d0813090/controllers/loadbalancer_controller.go#L198

To enable load balancing without exposing the service to the public VNI, some mechanism should be implemented
allowing to announce that route to the network specified via `networkRef`.

An idea to disambiguate between the public behavior and the internal behavior could be to have a `type` field in the
`LoadBalancer` `spec` that can be either `Public` or `Internal`.

Example manifest for the old use-case (public load balancer):
```yaml
# To specify a load balancer for the public network, we should have to use `type: Public`
apiVersion: networking.metalnet.onmetal.de/v1alpha1
kind: LoadBalancer
metadata:
  name: loadbalancer-sample-public
spec:
  type: Public # This is the current behavior
  ipFamily: IPv4
  ip: 10.0.0.1
  ports:
  - protocol: TCP
    port : 80
  nodeName: my-node
  networkRef:
    name: network-sample
```

Example manifest for the new use-case (internal load balancer):
```yaml
# To specify a load balancer for the network referenced via `networkRef`, we should have to use `type: Internal`
apiVersion: networking.metalnet.onmetal.de/v1alpha1
kind: LoadBalancer
metadata:
  name: loadbalancer-sample-internal
spec:
  type: Internal # The new behavior
  ipFamily: IPv4
  ip: 194.11.242.110
  ports:
  - protocol: TCP
    port : 80
  nodeName: my-node
  networkRef:
    name: network-sample
```

cc @gehoern @afritzler @ManuStoessel
