### ISSUE TITLE
Report NAT IP `port` / `endPort` in `NetworkInterface.Status.NatIP`

### ISSUE THREAD

**Issue by adracus** [ironcore-dev/metalnet#54]
# Summary

The NAT IP `port` / `endPort` should be reported as part of the `NetworkInterface` `Status`.

## Basic example

Example status would look like this:

```yaml
status:
  natIP:
    ip: 10.0.0.1
    port: 1024
    endPort: 1087
```

## Motivation

Currently, the information on what exact port is being used is lost after the reconciliation of the `NetworkInterface`.
Other controllers (e.g. `onmetal-api-net`'s `metalnetlet`) need to have the exact information to report back to the user whether
the expected NAT IP assignment took place.
